### ISSUE TITLE
Invite Company Admin Functionality Not Working

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1948]
## Summary

Describe the bug - a clear and concise description of what the bug is.

## Background

Error reported by Brian Waner:

UI Log:
```
main.js:1 Running in deployed services mode
6.js:1 errors: true
6.js:1 errors - missing_ccla: [object Object]
/#/cla/project/9e34f107-9fdc-4a82-981a-7159c4305665/user/38337046-faaf-4e8f-be0e-fefedc0c7657:1 Access to XMLHttpRequest at 'https://api.lfcla.com/v2/user/38337046-faaf-4e8f-be0e-fefedc0c7657/invite-company-admin' from origin 'https://contributor.lfcla.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
vendor.js:1 ERROR SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at e._error (9.js:1)
    at e.__tryOrUnsub (vendor.js:1)
    at e.error (vendor.js:1)
    at e._error (vendor.js:1)
    at e.error (vendor.js:1)
    at e._error (vendor.js:1)
    at e.error (vendor.js:1)
    at e.notifyError (vendor.js:1)
    at e._error (vendor.js:1)
(anonymous) @ vendor.js:1
api.lfcla.com/v2/user/38337046-faaf-4e8f-be0e-fefedc0c7657/invite-company-admin:1 Failed to load resource: net::ERR_FAILED
/#/cla/project/9e34f107-9fdc-4a82-981a-7159c4305665/user/38337046-faaf-4e8f-be0e-fefedc0c7657:1 Access to XMLHttpRequest at 'https://api.lfcla.com/v2/user/38337046-faaf-4e8f-be0e-fefedc0c7657/invite-company-admin' from origin 'https://contributor.lfcla.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
vendor.js:1 ERROR SyntaxError: Unexpected token o in JSON at position 1
```

API Logs:
```
2020-10-07T12:35:33.778-07:00
Copy
[ERROR] TypeError: create_event() got an unexpected keyword argument 'event_sumamry'
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 110, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 186, in invite_company_admin
    str(project_name), str(company_name)
  File "/var/task/cla/controllers/user.py", line 265, in invite_cla_manager
    contains_pii=True,
```

## Screenshots

![image.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/fce1234d-a765-4c4d-993b-f6c1bc629868)

## Environment

* Environment: PROD

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
@wanyaland pushed PR and is merged to DEV.

Up next: need to perform a PROD release.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/79e7aaa0-cbc4-4850-b201-954beb0a42ac)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8842c4a2-a2af-4280-9ee1-30a14921d64c)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4624d0ec-288a-47eb-ba47-83fc93ab49c0)
