### ISSUE TITLE
EasyCLA Bug Report: Cannot edit/remove contributors or add approval criteria

### ISSUE THREAD

**Issue by mrbobbytables** [communitybridge/easycla#3500]
## Summary

**NOTE:** This issue was reported in Slack. I'm posting here just to keep track

Cannot interact with CLAs on CLA dashboard

## Background

As a CLA Manager, when I click on edit on any button, the page locks up and becomes unusable.

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD (unknown on others)
* Browser:
  - [x] Chrome/Brave
  - [x] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Additional Context

Logs from the developer console

```
main-es2015.c1ba09563839f6a28906.js:23 Cannot get unsaved property from storage => notifications
(anonymous) @ main-es2015.c1ba09563839f6a28906.js:23
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,32
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,198
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,306
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,235
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,22
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,79
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,64
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,208
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,275
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,312
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,534
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,190
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,462
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,383
main-es2015.c1ba09563839f6a28906.js:2587 [GraphQL error]: Message: 502: Bad Gateway, Path: getCompanyContributorAcknowledgements,contributorsList,442
vendor-es2015.026245ac40c5185d7705.js:1 ERROR TypeError: Cannot read properties of null (reading 'photoUrl')
    at Object.updateDirectives (/12-es2015.ea478d73500a95acfebb.js:1:720594)
    at Object.updateDirectives (/vendor-es2015.026245ac40c5185d7705.js:1:389745)
    at Zc (/vendor-es2015.026245ac40c5185d7705.js:1:372220)
    at ru (/vendor-es2015.026245ac40c5185d7705.js:1:379387)
    at iu (/vendor-es2015.026245ac40c5185d7705.js:1:379048)
    at Zc (/vendor-es2015.026245ac40c5185d7705.js:1:372242)
    at ru (/vendor-es2015.026245ac40c5185d7705.js:1:379387)
    at iu (/vendor-es2015.026245ac40c5185d7705.js:1:379048)
    at Zc (/vendor-es2015.026245ac40c5185d7705.js:1:372242)
    at ru (/vendor-es2015.026245ac40c5185d7705.js:1:379387)
Yn @ vendor-es2015.026245ac40c5185d7705.js:1
0:1          Failed to load resource: the server responded with a status of 403 ()
%EF%BF%BD.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
1516360001751:1          Failed to load resource: the server responded with a status of 403 ()
[.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
0:1          Failed to load resource: the server responded with a status of 403 ()
```

## Acceptance Criteria

For the buttons on the EasyCLA console to work as intended

**Comment by dealako** [comment]
Added pagination to the API as part of PR: https://github.com/communitybridge/easycla/pull/3497 - awaiting UX team updates to add pagination client-side support.

**Comment by WillsonHG** [comment]
@mrbobbytables I believe the issue with loading the console and being able to use the UI was resolved with the pagination introduced to the Approval Criteria. This greatly reduced the loading time and all buttons should now be working - can you confirm?

Note: Pagination was added to both contributor acknowledgements and approval criteria sections in the api - In the UI it has only been implemented in the approval criteria so far, We are also now implementing in event log.

**Comment by WillsonHG** [comment]
closing this and tracking upgrades to corporate console in [3575](https://github.com/communitybridge/easycla/issues/3575)
