### ISSUE TITLE
Getting an error when trying to add approval criteria at easycla contributor

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4201]
## Summary

Getting an error when trying to add approval criteria at easycla contributor

## Steps

1. Login company contributor
2. Search & easycla page of project
3. Add new approval criteria  

## Expected behavior
Contributor should add under approval list

## Actual behavior
Getting an error when trying to add approval criteria at easycla contributor

## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/2ed2c5ad-5cc9-4a76-90ee-fe5623b6dfb1)

## Error on console
`Pattern attribute value /^[a-z\d](?:[a-z\d]|[-_](?=[a-z\d])){0,38}$/i is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: //^[a-z\d](?:[a-z\d]|[-_](?=[a-z\d])){0,38}$/i/v: Invalid character in character class
add-contributor.component.html:68 ERROR TypeError: Cannot read properties of null (reading '0')
    at AddContributorComponent.patchApprovalList (add-contributor.component.ts:158:34)
    at AddContributorComponent.onSubmit (add-contributor.component.ts:94:12)
    at Object.handleEvent (add-contributor.component.html:72:21)
    at handleEvent (core.js:38098:77)
    at callWithDebugContext (core.js:39716:1)
    at Object.debugHandleEvent [as handleEvent] (core.js:39352:1)
    at dispatchEvent (core.js:25818:1)
    at core.js:37030:1
    at HTMLButtonElement.<anonymous> (platform-browser.js:1789:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391:1)`

**Comment by thakurveerendras** [comment]
![image](https://github.com/communitybridge/easycla/assets/75417507/8bcba763-b59e-4935-87b4-d78c92571e7c)

**Comment by nickmango** [comment]
@thakurveerendras is this still reproducible ?

**Comment by PoojaPanjwani204** [comment]
It is resolved now.
![image](https://github.com/communitybridge/easycla/assets/87165074/a0975c3f-526a-4d5f-b49d-2c6bdc201b90)
