### ISSUE TITLE
CCLA Signature Query Error

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#486]
## Summary

We have an issue in PROD when querying the CNCF signatures.

## Background

```
17:22:40
2020-01-10T17:22:40 INFO cla: Requested: POST /v2/check-prepare-employee-signature application/json
2020-01-10T17:22:40 INFO cla: Requested: POST /v2/check-prepare-employee-signature application/json
17:22:41
2020-01-10T17:22:41 DEBUG cla: Check and prepare employee signature for project: d8cead54-92b7-48c5-a2c8-b1e295e8f7f1, company: 40f2d23b-fd1e-4f5d-acc1-d9ed425adf54, user: 729b1a99-b747-4745-a70f-5b7b83a0bcbb
17:22:41
2020-01-10T17:22:41 DEBUG cla: Project exists for: project: d8cead54-92b7-48c5-a2c8-b1e295e8f7f1, company: 40f2d23b-fd1e-4f5d-acc1-d9ed425adf54, user: 729b1a99-b747-4745-a70f-5b7b83a0bcbb
17:22:41
2020-01-10T17:22:41 DEBUG cla: Company exists for: project: d8cead54-92b7-48c5-a2c8-b1e295e8f7f1, company: 40f2d23b-fd1e-4f5d-acc1-d9ed425adf54, user: 729b1a99-b747-4745-a70f-5b7b83a0bcbb
17:22:41
2020-01-10T17:22:41 DEBUG cla: User exists for: project: d8cead54-92b7-48c5-a2c8-b1e295e8f7f1, company: 40f2d23b-fd1e-4f5d-acc1-d9ed425adf54, user: 729b1a99-b747-4745-a70f-5b7b83a0bcbb
17:22:41
2020-01-10T17:22:41 INFO cla: Loading signature by project for project_id: d8cead54-92b7-48c5-a2c8-b1e295e8f7f1
17:22:41
2020-01-10T17:22:41 INFO cla: Loaded signature by project for project_id: d8cead54-92b7-48c5-a2c8-b1e295e8f7f1
17:22:42
2020-01-10T17:22:42 INFO cla: 108.168.239.92 - - [2020-01-10 17:22:42.933196] POST /v2/check-prepare-employee-signature 200 OK - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
17:22:42
[ERROR] TypeError: 'NoneType' object is not iterable Traceback (most recent call last):   File "/var/task/wsgi_handler.py", line 108, in handler     return serverless_wsgi.handle_request(wsgi_app, event, context)   File "/var/task/serverless_wsgi.py", line 173, in handle_request     response = Response.from_app(app, environ)   File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_
[ERROR] TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 108, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 1235, in check_and_prepare_employee_signature
    return cla.controllers.signing.check_and_prepare_employee_signature(project_id, company_id, user_id)
  File "/var/task/cla/controllers/signing.py", line 100, in check_and_prepare_employee_signature
    return get_signing_service().check_and_prepare_employee_signature(str(project_id), str(company_id), str(user_id))
  File "/var/task/cla/models/docusign_models.py", line 382, in check_and_prepare_employee_signature
    signature_reference_id=company.get_company_id()
  File "/var/task/cla/models/dynamo_models.py", line 1947, in get_signatures_by_project
    for signature_model in signature_generator:
  File "/var/task/pynamodb/pagination.py", line 183, in __next__
    item = self._map_fn(item)
  File "/var/task/pynamodb/models.py", line 533, in from_raw_data
    kwargs[attr_name] = attr.deserialize(attr.get_value(value))
  File "/var/task/pynamodb/attributes.py", line 973, in deserialize
    for v in values:
END RequestId: aa1f4275-dd21-4511-b6b0-b3f145f2a9db
```

## Expected behavior

The query should run without error.

## Environment

PROD

* Environment: PROD 

## Acceptance Criteria

Resolve the database query error. Push changes to DEV, STAGING, and PROD.

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

Product Support Ticket: https://jira.linuxfoundation.org/servicedesk/customer/portal/4/SUPPORT-839

**Comment by dealako** [comment]
Use case:
1. Create PR for CNCF project
1. EasyCLA bot Fails the PR
1. User clicks through to EasyCLA
1. User selects Corporate CLA
1. User searches and selects their company
1. UI spins while performing the CCLA signature lookup

![Screen Shot 2020-01-10 at 11 08 24 AM](https://user-images.githubusercontent.com/519609/72179340-902b6f80-3399-11ea-999a-cae8d007d639.png)
