### ISSUE TITLE
Contributor Console: Error when selecting company

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#510]
## Summary

User is unable to select company to verify with for CCLA. UI spins and is unresponsive.

Error: 
08:23:38
[ERROR] NameError: name 'Condition' is not defined Traceback (most recent call last):   File "/var/task/wsgi_handler.py", line 108, in handler     return serverless_wsgi.handle_request(wsgi_app, event, context)   File "/var/task/serverless_wsgi.py", line 173, in handle_request     response = Response.from_app(app, environ)   File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_ap
[ERROR] NameError: name 'Condition' is not defined
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 108, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 1235, in check_and_prepare_employee_signature
    return cla.controllers.signing.check_and_prepare_employee_signature(project_id, company_id, user_id)
  File "/var/task/cla/controllers/signing.py", line 100, in check_and_prepare_employee_signature
    return get_signing_service().check_and_prepare_employee_signature(str(project_id), str(company_id), str(user_id))
  File "/var/task/cla/models/docusign_models.py", line 386, in check_and_prepare_employee_signature
    project_id=project_id
  File "/var/task/cla/models/dynamo_models.py", line 2006, in get_ccla_signatures_by_company_project
    filter_condition = create_filter(signature_attributes, SignatureModel)
  File "/var/task/cla/models/dynamo_models.py", line 76, in create_filter
    condition if not isinstance(filter_condition, Condition) else filter_condition & condition

* Environment: PROD 

## References

https://jira.linuxfoundation.org/browse/SUPPORT-873

https://github.com/cloudfoundry/java-buildpack/pull/771 User's PR in CFF repo at 1:53am EST failed.
 User later chose ICLA instead and CLA bot edited comment to pass at 3:17am with ICLA

**Comment by dealako** [comment]
Added import for Condition. Pushed release: https://github.com/communitybridge/easycla/releases/tag/v0.1.81.p12
