### ISSUE TITLE
Contributor Console: Unable to choose your company.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#516]
## Summary

A contributor from Gerrit or GitHub is unable to select their company to verify affiliation with.

[ERROR] NameError: name 'preprocessed_pattern' is not defined Traceback (most recent call last):   File "/var/task/wsgi_handler.py", line 108, in handler     return serverless_wsgi.handle_request(wsgi_app, event, context)   File "/var/task/serverless_wsgi.py", line 173, in handle_request     response = Response.from_app(app, environ)   File "/var/task/werkzeug/wrappers/base_response.py", line 287,
2020/01/22/[$LATEST]35e89a6a0d404e9d996dd0499e3f5d62
[ERROR] NameError: name 'preprocessed_pattern' is not defined
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 108, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 1334, in check_and_prepare_employee_signature
    return cla.controllers.signing.check_and_prepare_employee_signature(project_id, company_id, user_id)
  File "/var/task/cla/controllers/signing.py", line 100, in check_and_prepare_employee_signature
    return get_signing_service().check_and_prepare_employee_signature(str(project_id), str(company_id), str(user_id))
  File "/var/task/cla/models/docusign_models.py", line 402, in check_and_prepare_employee_signature
    if not user.is_whitelisted(ccla_signature):
  File "/var/task/cla/models/dynamo_models.py", line 1557, in is_whitelisted
    self.log_debug(f"Did not match email: {email} with domain: {preprocessed_pattern}")

* Environment:  PROD

**Comment by dealako** [comment]
This issue is due to a processing error on the corporate console whitelist handling. Added unit tests and resolved the issue.
