### ISSUE TITLE
Error and wrong behavior when sending ccla for signature

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#579]
## Summary

In the corporate console, when a CLA manager submits the form to send the CLA to another person to sign, the system is looking at the company_acl list in the companies table instead of looking at the signature_acl in the signatures table. This results in the wrong cla manager's name being filled in on the CCLA and can sometimes result in an error. The entire behavior of this process needs to be reviewed.

[ERROR] AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 110, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 1195, in request_corporate_signature
    return_url)
  File "/var/task/cla/controllers/signing.py", line 62, in request_corporate_signature
    return_url_type, return_url)
  File "/var/task/cla/models/docusign_models.py", line 667, in request_corporate_signature
    if manager.get_user_name().lower() == authority_name.lower():

## Expected behavior

The CLA manager who is sending the CCLA out for signature should be the cla manager listed on the document. This name should come from the new signature_acl that is created instead of from the company_acl.

**Comment by dealako** [comment]
Note to self: In this case, we need to lookup Corporate Signature ACL members (CLA Managers) instead of Company ACL (Company Managers).

**Comment by WillsonHG** [comment]
@dealako I've verified on dev that I am added as the initial cla manager correctly even when there are other cla managers for the project.

**Comment by dealako** [comment]
Verfied.
