### ISSUE TITLE
502 on request-individual-signature

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#675]
## Summary

A contributor from github selects "individual" and the ICLA is never created due to a 502

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

1. https://github.com/cloudfoundry/bosh-deployment/pull/389
1. attempt to sign an individual cla
1. observe no icla is created and inspect page for error information.

## Expected behavior

An icla should be created through docusign and the pdf button should activate for the contributor to press to sign.

## Screenshots

![image](https://user-images.githubusercontent.com/46732999/76427081-40a9f580-6382-11ea-91ad-cbfe13346058.png)

## Environment

Please complete the following information:

* Environment: PROD

## Additional Context


05:42:46
[ERROR] HTTPError: HTTP Error 403: Forbidden Traceback (most recent call last):   File "/var/task/wsgi_handler.py", line 110, in handler     return serverless_wsgi.handle_request(wsgi_app, event, context)   File "/var/task/serverless_wsgi.py", line 173, in handle_request     response = Response.from_app(app, environ)   File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app     
[ERROR] HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 110, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 1151, in request_individual_signature
    return cla.controllers.signing.request_individual_signature(project_id, user_id, return_url_type, return_url)
  File "/var/task/cla/controllers/signing.py", line 32, in request_individual_signature
    return signing_service.request_individual_signature(str(project_id), str(user_id), return_url)
  File "/var/task/cla/models/docusign_models.py", line 233, in request_individual_signature
    self.populate_sign_url(signature, callback_url, default_values=default_cla_values)
  File "/var/task/cla/models/docusign_models.py", line 982, in populate_sign_url
    pdf = self.get_document_resource(document.get_document_s3_url())
  File "/var/task/cla/models/docusign_models.py", line 1299, in get_document_resource
    return urllib.request.urlopen(url)
  File "/var/lang/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/var/lang/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/var/lang/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/var/lang/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/var/lang/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/var/lang/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-apiv2;stream=2020/03/11/%5B$LATEST%5D1666449e7e234a9baf91ddf7cce65f02;refid=35322270004216406335500381722906196425572134013043736616;reftime=1583905366828

## References
https://jira.linuxfoundation.org/projects/SUPPORT/queues/custom/50/SUPPORT-993

**Comment by WillsonHG** [comment]
Errors in cloudwatch also coming from presto 
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-apiv2;stream=2020/03/11/%5B$LATEST%5D030f1c627fba4ec589f7f4e0efd60200;refid=35322717696627032271833770659881852607068229958156943398;reftime=1583925442050

**Comment by WillsonHG** [comment]
This appears to have been resolved by david's script to update s3 template permissions, letting this open just a bit longer to make sure.

**Comment by hchiao1** [comment]
Seems like the link show up this time, however, it doesn't auto update the PR. Still having  EasyCLA — Missing CLA Authorization error.

**Comment by dealako** [comment]
Reviewed and updated template file permissions currently stored in AWS s3 for DEV, STAGING, and PROD.  Ran script to ensure:

- `Content-Type` is `application/pdf`
- Permissions are `public_read`

I opened a separate issue to review and confirm we are setting the permissions correctly when the template is created by the EasyCLA system: #676

**Comment by WillsonHG** [comment]
this is resolved.

**Comment by nirupamav** [comment]
Verified that user/contributor is able to sign the ICLA 
![image](https://user-images.githubusercontent.com/60865903/77288017-ee12f680-6cfc-11ea-838a-c0405010a632.png)
