### ISSUE TITLE
API - Python PR Number Parse Error

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#784]
## Summary

API - Python PR Number Parse Error

## Background

@wanyaland please review and diagnose. Why are we getting a trailing ')' character on the PR number: `876)`??  Is this from GH? or other API.

```
15:25:53 START RequestId: 7d6265b4-6d6f-41d8-af93-07de795d2d6f Version: $LATEST
15:25:53 2020-03-31T15:25:53 INFO cla: Requested: GET /v2/repository-provider/github/sign/1797134/40684777/876)
15:25:53 2020-03-31T15:25:53 DEBUG cla: Initiating GitHub sign request for repository 40684777
15:25:53 2020-03-31T15:25:53 DEBUG cla: Getting PR 876) from GitHub repository 40684777
15:25:53 2020-03-31T15:25:53 DEBUG cla: Initializing github application - installation_id: 1797134, app id: 17893, private key (minus header): MIIEpA...
15:25:53 2020-03-31T15:25:53 INFO cla: 77.67.54.48 - - [2020-03-31 15:25:53.369187] GET /v2/repository-provider/github/sign/1797134/40684777/876) 200 OK - Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
15:25:53 [ERROR] ValueError: invalid literal for int() with base 10: '876)' Traceback (most recent call last): File "/var/task/wsgi_handler.py", line 110, in handler     return serverless_wsgi.handle_request(wsgi_app, event, context)   File "/var/task/serverless_wsgi.py", line 173, in handle_request     response = Response.from_app(app, environ)   File "/var/task/werkzeug/wrappers/base_response.py", line
[ERROR] ValueError: invalid literal for int() with base 10: '876)'
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 110, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 1336, in sign_request
    request)
  File "/var/task/cla/controllers/repository_service.py", line 35, in sign_request
    return service.sign_request(installation_id, github_repository_id, change_request_id, request)
  File "/var/task/cla/models/github_models.py", line 94, in sign_request
    origin_url = self.get_return_url(github_repository_id, change_request_id, installation_id)
  File "/var/task/cla/models/github_models.py", line 262, in get_return_url
    pull_request = self.get_pull_request(github_repository_id, change_request_id, installation_id)
  File "/var/task/cla/models/github_models.py", line 359, in get_pull_request
    return repo.get_pull(int(pull_request_number))
```

## Expected behavior

Need to sanitize request and filter out bad data.

## Environment

Please complete the following information:

* Environment: STAGING and PROD 
* OS: \[e.g. iOS\]
* Browser \[e.g. chrome, safari\]
* Version \[e.g. 22\]

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Deployed change to DEV.  If this issue comes up again, we can revisit.  Added traps.
